apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relentless-worker.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "relentless-worker.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "relentless-worker.name" . }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "relentless-worker.fullname" . }}-config
