apiVersion: v1
kind: Service
metadata:
  name: {{ include "relentless-worker.fullname" . }}
  labels:
    app: {{ include "relentless-worker.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "relentless-worker.name" . }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
