apiVersion: v1
kind: Service
metadata:
  name: relentless-api
  namespace: default
  labels:
    app: relentless-api
spec:
  selector:
    app: relentless-api
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080