apiVersion: v1
kind: Service
metadata:
  name: relentless-prometheus
  namespace: default
spec:
  type: ClusterIP
  selector:
    prometheus: relentless-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
