apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: relentless-prometheus
  namespace: default
spec:
  replicas: 1
  serviceAccountName: relentless-prometheus
  additionalScrapeConfigs:
    name: prometheus-additional-scrape-configs
    key: prometheus-additional-scrape-configs.yaml
  serviceMonitorSelector:
    matchLabels:
      app: relentless
