apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: relentless-worker
  namespace: default
  labels:
    app: relentless
spec:
  selector:
    matchLabels:
      app: relentless-worker
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - path: /metrics
      port: metrics
