apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-lag-exporter
  namespace: default
  labels:
    app: kafka-lag-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-lag-exporter
  template:
    metadata:
      labels:
        app: kafka-lag-exporter
    spec:
      containers:
        - name: kafka-lag-exporter
          image: danielqsj/kafka-exporter:latest
          args:
            - --kafka.server=relentless-kafka-kafka-bootstrap.kafka:9092
            - --web.listen-address=:9308
            - --web.telemetry-path=/metrics
          ports:
            - name: metrics
              containerPort: 9308
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 100m
