apiVersion: v1
kind: Service
metadata:
  name: relentless-grafana
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: relentless-grafana
  ports:
    - port: 3000
      targetPort: 3000
