apiVersion: v1
kind: Service
metadata:
  name: relentless-neo4j
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: relentless-neo4j
  ports:
    - name: http
      port: 7474
      targetPort: 7474
    - name: bolt
      port: 7687
      targetPort: 7687
