apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "relentless-api.fullname" . }}-config
data:
  KAFKA_BROKER: {{ .Values.env.KAFKA_BROKER | quote }}
  KAFKA_TOPIC: {{ .Values.env.KAFKA_TOPIC | quote }}
  REDIS_ADDR: {{ .Values.env.REDIS_ADDR | quote }}
