apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "relentless-api.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "relentless-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "relentless-api.name" . }}
    spec:
      serviceAccountName: {{ include "relentless-api.serviceAccountName" . }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "relentless-api.fullname" . }}-config
