{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "relentless-api.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "relentless-api.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "relentless-api.fullname" . }}-role
{{- end }}
