apiVersion: v1
kind: Service
metadata:
  name: relentless-worker
  namespace: default
  labels:
    app: relentless-worker
spec:
  type: ClusterIP
  selector:
    app: relentless-worker
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090
